<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from searchactiondesigner/xml/schema/CRM/Searchactiondesigner/SearchTaskField.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:5d181508db15fb17759374152fcf195c)
 */
use CRM_Searchactiondesigner_ExtensionUtil as E;

/**
 * Database access object for the SearchTaskField entity.
 */
class CRM_Searchactiondesigner_DAO_SearchTaskField extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_search_task_field';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = FALSE;

  /**
   * Unique SearchTaskField ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * FK to Search Task
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $search_task_id;

  /**
   * @var string
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $name;

  /**
   * @var string
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $title;

  /**
   * @var string
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $type;

  /**
   * @var bool|string
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $is_required;

  /**
   * @var string
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $default_value;

  /**
   * @var string
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $configuration;

  /**
   * @var int|string
   *   (SQL type: int)
   *   Note that values will be retrieved from the database as a string.
   */
  public $weight;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_search_task_field';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Search Task Fields') : E::ts('Search Task Field');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'search_task_id', 'civicrm_search_task', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Unique SearchTaskField ID'),
          'required' => TRUE,
          'where' => 'civicrm_search_task_field.id',
          'table_name' => 'civicrm_search_task_field',
          'entity' => 'SearchTaskField',
          'bao' => 'CRM_Searchactiondesigner_DAO_SearchTaskField',
          'localizable' => 0,
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'search_task_id' => [
          'name' => 'search_task_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Search Task'),
          'description' => E::ts('FK to Search Task'),
          'required' => TRUE,
          'where' => 'civicrm_search_task_field.search_task_id',
          'table_name' => 'civicrm_search_task_field',
          'entity' => 'SearchTaskField',
          'bao' => 'CRM_Searchactiondesigner_DAO_SearchTaskField',
          'localizable' => 0,
          'FKClassName' => 'CRM_Searchactiondesigner_DAO_SearchTask',
          'add' => NULL,
        ],
        'name' => [
          'name' => 'name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Name'),
          'required' => FALSE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_search_task_field.name',
          'table_name' => 'civicrm_search_task_field',
          'entity' => 'SearchTaskField',
          'bao' => 'CRM_Searchactiondesigner_DAO_SearchTaskField',
          'localizable' => 0,
          'add' => NULL,
        ],
        'title' => [
          'name' => 'title',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Title'),
          'required' => TRUE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_search_task_field.title',
          'table_name' => 'civicrm_search_task_field',
          'entity' => 'SearchTaskField',
          'bao' => 'CRM_Searchactiondesigner_DAO_SearchTaskField',
          'localizable' => 0,
          'add' => NULL,
        ],
        'type' => [
          'name' => 'type',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Type'),
          'required' => TRUE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_search_task_field.type',
          'table_name' => 'civicrm_search_task_field',
          'entity' => 'SearchTaskField',
          'bao' => 'CRM_Searchactiondesigner_DAO_SearchTaskField',
          'localizable' => 0,
          'add' => NULL,
        ],
        'is_required' => [
          'name' => 'is_required',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Is required'),
          'required' => FALSE,
          'where' => 'civicrm_search_task_field.is_required',
          'table_name' => 'civicrm_search_task_field',
          'entity' => 'SearchTaskField',
          'bao' => 'CRM_Searchactiondesigner_DAO_SearchTaskField',
          'localizable' => 0,
          'add' => NULL,
        ],
        'default_value' => [
          'name' => 'default_value',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Default Value'),
          'required' => FALSE,
          'where' => 'civicrm_search_task_field.default_value',
          'table_name' => 'civicrm_search_task_field',
          'entity' => 'SearchTaskField',
          'bao' => 'CRM_Searchactiondesigner_DAO_SearchTaskField',
          'localizable' => 0,
          'add' => NULL,
        ],
        'configuration' => [
          'name' => 'configuration',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Configuration'),
          'required' => FALSE,
          'where' => 'civicrm_search_task_field.configuration',
          'table_name' => 'civicrm_search_task_field',
          'entity' => 'SearchTaskField',
          'bao' => 'CRM_Searchactiondesigner_DAO_SearchTaskField',
          'localizable' => 0,
          'serialize' => self::SERIALIZE_JSON,
          'add' => NULL,
        ],
        'weight' => [
          'name' => 'weight',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Weight'),
          'required' => FALSE,
          'where' => 'civicrm_search_task_field.weight',
          'table_name' => 'civicrm_search_task_field',
          'entity' => 'SearchTaskField',
          'bao' => 'CRM_Searchactiondesigner_DAO_SearchTaskField',
          'localizable' => 0,
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'search_task_field', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'search_task_field', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
