<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2019
 *
 * Generated from /buildkit/build/search/sites/default/files/civicrm/ext/searchactiondesigner/xml/schema/CRM/Searchactiondesigner/SearchTask.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:c759615f44963ee0ac40d2bbe9b8992a)
 */

/**
 * Database access object for the SearchTask entity.
 */
class CRM_Searchactiondesigner_DAO_SearchTask extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  static $_tableName = 'civicrm_search_task';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  static $_log = FALSE;

  /**
   * Unique SearchTask ID
   *
   * @var int unsigned
   */
  public $id;

  /**
   * @var string
   */
  public $title;

  /**
   * @var string
   */
  public $name;

  /**
   * @var text
   */
  public $description;

  /**
   * @var text
   */
  public $success_message;

  /**
   * @var text
   */
  public $help_text;

  /**
   * @var string
   */
  public $type;

  /**
   * @var boolean
   */
  public $is_active;

  /**
   * @var int unsigned
   */
  public $status;

  /**
   * @var int unsigned
   */
  public $records_per_batch;

  /**
   * @var string
   */
  public $source_file;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_search_task';
    parent::__construct();
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Searchactiondesigner_ExtensionUtil::ts('Unique SearchTask ID'),
          'required' => TRUE,
          'table_name' => 'civicrm_search_task',
          'entity' => 'SearchTask',
          'bao' => 'CRM_Searchactiondesigner_DAO_SearchTask',
          'localizable' => 0,
        ],
        'title' => [
          'name' => 'title',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Searchactiondesigner_ExtensionUtil::ts('Title'),
          'required' => TRUE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'table_name' => 'civicrm_search_task',
          'entity' => 'SearchTask',
          'bao' => 'CRM_Searchactiondesigner_DAO_SearchTask',
          'localizable' => 0,
        ],
        'name' => [
          'name' => 'name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Searchactiondesigner_ExtensionUtil::ts('Name'),
          'required' => FALSE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'table_name' => 'civicrm_search_task',
          'entity' => 'SearchTask',
          'bao' => 'CRM_Searchactiondesigner_DAO_SearchTask',
          'localizable' => 0,
        ],
        'description' => [
          'name' => 'description',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => CRM_Searchactiondesigner_ExtensionUtil::ts('Description'),
          'required' => FALSE,
          'table_name' => 'civicrm_search_task',
          'entity' => 'SearchTask',
          'bao' => 'CRM_Searchactiondesigner_DAO_SearchTask',
          'localizable' => 0,
        ],
        'success_message' => [
          'name' => 'success_message',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => CRM_Searchactiondesigner_ExtensionUtil::ts('Success Message'),
          'required' => FALSE,
          'table_name' => 'civicrm_search_task',
          'entity' => 'SearchTask',
          'bao' => 'CRM_Searchactiondesigner_DAO_SearchTask',
          'localizable' => 0,
        ],
        'help_text' => [
          'name' => 'help_text',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => CRM_Searchactiondesigner_ExtensionUtil::ts('Help text'),
          'required' => FALSE,
          'table_name' => 'civicrm_search_task',
          'entity' => 'SearchTask',
          'bao' => 'CRM_Searchactiondesigner_DAO_SearchTask',
          'localizable' => 0,
        ],
        'type' => [
          'name' => 'type',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Searchactiondesigner_ExtensionUtil::ts('Type'),
          'required' => TRUE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'table_name' => 'civicrm_search_task',
          'entity' => 'SearchTask',
          'bao' => 'CRM_Searchactiondesigner_DAO_SearchTask',
          'localizable' => 0,
        ],
        'is_active' => [
          'name' => 'is_active',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => CRM_Searchactiondesigner_ExtensionUtil::ts('Is active'),
          'required' => TRUE,
          'table_name' => 'civicrm_search_task',
          'entity' => 'SearchTask',
          'bao' => 'CRM_Searchactiondesigner_DAO_SearchTask',
          'localizable' => 0,
        ],
        'status' => [
          'name' => 'status',
          'type' => CRM_Utils_Type::T_INT,
          'title' => CRM_Searchactiondesigner_ExtensionUtil::ts('Status'),
          'required' => FALSE,
          'default' => '0',
          'table_name' => 'civicrm_search_task',
          'entity' => 'SearchTask',
          'bao' => 'CRM_Searchactiondesigner_DAO_SearchTask',
          'localizable' => 0,
        ],
        'records_per_batch' => [
          'name' => 'records_per_batch',
          'type' => CRM_Utils_Type::T_INT,
          'title' => CRM_Searchactiondesigner_ExtensionUtil::ts('Number of records per batch'),
          'required' => TRUE,
          'default' => '25',
          'table_name' => 'civicrm_search_task',
          'entity' => 'SearchTask',
          'bao' => 'CRM_Searchactiondesigner_DAO_SearchTask',
          'localizable' => 0,
        ],
        'source_file' => [
          'name' => 'source_file',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Searchactiondesigner_ExtensionUtil::ts('Source File'),
          'required' => FALSE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'table_name' => 'civicrm_search_task',
          'entity' => 'SearchTask',
          'bao' => 'CRM_Searchactiondesigner_DAO_SearchTask',
          'localizable' => 0,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'search_task', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'search_task', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
